### ISSUE TITLE
Make make_request method public

### ISSUE THREAD

**Issue by hamzaali00001** [ConvertKit/ConvertKitSDK-PHP#11]
Can you convert the make_request method from private to public? This will allow users to make requests to API endpoints whose methods are not implemented in the library?

For Example:

I want to get a list of all tags by calling v3/tags but there is no such method. How could I do that?

**Comment by tnorthcutt** [comment]
Hi @hamzaali00001, I'd certainly welcome a PR to change this. Thanks!

**Comment by hamzaali00001** [comment]
Just Pushed the pull request.

https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/12

**Comment by tnorthcutt** [comment]
Closed in #12! Thanks @hamzaali00001
