### ISSUE TITLE
get_subscriber_id() causes 429 "Too many requests" API error when total pages > 120

### ISSUE THREAD

**Issue by modelm** [ConvertKit/ConvertKitSDK-PHP#21]
The exact number of pages seems to vary, but calling this function is very slow and eventually causes the API to throw a 429 error for an account with lots of subscribers, because it queries the API for all subscribers and searches the results instead of searching the API directly for the provided email.

It is possible to search by email when listing subscribers using the `email_address` parameter according to https://developers.convertkit.com/#list-subscribers

Adding the `email_address` parameter to `$options` in `get_subscriber_id()` should fix this issue.

**Comment by duplaja** [comment]
Just ran into this one myself. I'd pulled the SDK into my project prior to your posting, so didn't see it in open issues, and spent the last couple hours scratching my head. Found the issue, came here to post, and saw your fix. Thank you!

**Comment by modelm** [comment]
Here's a workaround until the fix is merged, just make a direct request to /subscribers with the necessary options set instead of using get_subscriber_id(): 

```
		$response = $convertkit_client->make_request('v3/subscribers', 'GET', [
			'api_secret' => $api_secret,
			'status' => 'all',
			'email_address' => $user_email,
		]);
		$subscriber = $response->subscribers[0] ?? false;
```

**Comment by mnwalker** [comment]
If it helps anyone you can use this fork https://github.com/mnwalker/convertkitsdk-php

Fixes this issue which also gives a massive performance boost if have many subscribers.
And updated the guzzle version in composer so will work with more modern framework releases.

Have sent @ConvertKit a pull request but will need someone to merge them.

**Comment by mnwalker** [comment]
#29

**Comment by n7studios** [comment]
Fixed in https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/31. Thanks!
