### ISSUE TITLE
Package update

### ISSUE THREAD

**Issue by nam-co** [ConvertKit/ConvertKitSDK-PHP#25]
Hi, I was wondering if this package is going to be updated, the last commit was 2 years a. go,  with the recent releases of php will this be upgraded?

Thanks

**Comment by jhull** [comment]
I asked Convertkit support directly about this and the response was that they were going to hire someone...maybe...(and that was a year ago) so....

**Comment by n7studios** [comment]
It'll be updated by March 31st 2023, with a version `1.0` addressing outstanding dependency issues and bugs. Thanks!
