### ISSUE TITLE
Installation Error requires guzzle ^6.3 and I have 7

### ISSUE THREAD

**Issue by dylanglockler** [ConvertKit/ConvertKitSDK-PHP#26]
The command:

composer require convertkit/convertkitapi:dev-master

Problem 1
    - Root composer.json requires convertkit/convertkitapi dev-master -> satisfiable by convertkit/convertkitapi[dev-master].
    - convertkit/convertkitapi dev-master requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

My guzzle version from composer.json:

        "guzzlehttp/guzzle": "^7.0.1",

**Comment by dylanglockler** [comment]
Change to update composer.json with:

"guzzlehttp/guzzle": "^6.5|^7.0.1",

**Comment by mnwalker** [comment]
Better change would be below which will support future minor versions too.
"guzzlehttp/guzzle": "^6.5|^7.0",

**Comment by n7studios** [comment]
Addressing in https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/28, to be released as version `1.0`, rather than a potentially breaking change into the unversioned `dev-master`. Thanks!
