### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by silasrm** [ConvertKit/ConvertKitSDK-PHP#4]
Hi Guys,

I'm added this repo to Packagist. Follow instructions and contact the Packagist to owned like as mantainers:

This package is not auto-updated. Please set up the GitHub Hook for Packagist so that it gets updated whenever you push!
There is no license information available for the latest version (dev-master) of this package.

**Comment by tnorthcutt** [comment]
@silasrm would you mind removing this from Packagist, and then I can re-add it under my username?

**Comment by silasrm** [comment]
Done. Try now.

**Comment by tnorthcutt** [comment]
This is on Packagist now: https://packagist.org/packages/convertkit/convertkitapi
